apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-superuser-secret-external-secret
  namespace: cnpg-system
spec:
  refreshInterval: 720h # 1 month
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-superuser-secret
  data:
  - secretKey: username # key in Kubernetes Secret
    remoteRef:
      key: cnpg-superuser-secret # key in the secret store
      property: username # property in the secret store secret
  - secretKey: password # key in Kubernetes Secret
    remoteRef:
      key: cnpg-superuser-secret # key in the secret store
      property: password # property in the secret store secret