apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-password-external-secret
  namespace: redis-sentinel
spec:
  refreshInterval: 720h # 1 month
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: redis-password-secret
  data:
  - secretKey: redis-password # key in Kubernetes Secret
    remoteRef:
      key: redis-password # key in the secret store
      property: redis-password # property in the secret store secret