apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-external-secret
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: example-synced-secret
  data:
  - secretKey: foo-bar # key in Kubernetes Secret
    remoteRef:
      key: foo # key in the secret store
      property: bar # property in the secret store secret