apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials-external-secret
  namespace: kube-prometheus-stack
spec:
  refreshInterval: 720h # 1 month
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
  data:
  - secretKey: admin-user # key in Kubernetes Secret
    remoteRef:
      key: grafana-admin-credentials # key in the secret store
      property: admin-user # property in the secret store secret
  - secretKey: admin-password # key in Kubernetes Secret
    remoteRef:
      key: grafana-admin-credentials # key in the secret store
      property: admin-password # property in the secret store secret