apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloud-credentials-external-secret
  namespace: velero
spec:
  refreshInterval: 720h # 1 month
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: cloud-credentials
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id = {{ .ACCESS_KEY_ID }}
          aws_secret_access_key = {{ .ACCESS_SECRET_KEY }}
  data:
  - secretKey: ACCESS_KEY_ID # key in Kubernetes Secret
    remoteRef:
      key: cnpg-backup-s3-creds # key in the secret store
      property: ACCESS_KEY_ID # property in the secret store secret
  - secretKey: ACCESS_SECRET_KEY # key in Kubernetes Secret
    remoteRef:
      key: cnpg-backup-s3-creds # key in the secret store
      property: ACCESS_SECRET_KEY # property in the secret store secret