apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-password-external-secret
  namespace: harbor
spec:
  refreshInterval: 720h # 1 month
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: harbor-admin-password
  data:
  - secretKey: HARBOR_ADMIN_PASSWORD # key in Kubernetes Secret
    remoteRef:
      key: harbor-admin-password # key in the secret store
      property: HARBOR_ADMIN_PASSWORD # property in the secret store secret