apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-cnpg-password-external-secret
  namespace: harbor
spec:
  refreshInterval: 720h # 1 month
  secretStoreRef:
    name: cluster-secret-store-backend
    kind: ClusterSecretStore
  target:
    name: harbor-cnpg-password
  data:
  - secretKey: password # key in Kubernetes Secret
    remoteRef:
      key: cnpg-superuser-secret # key in the secret store
      property: password # property in the secret store secret